# Generated by Django 5.0.6 on 2024-07-08 21:21

import core.models
import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Image'),
        ),
    ]
