# Generated by Django 5.0.6 on 2024-07-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='altitudealti',
        ),
        migrations.AddField(
            model_name='project',
            name='local',
            field=models.CharField(default='', max_length=100, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('In progress', 'In progress'), ('Finished', 'Finished'), ('Canceled', 'Canceled')], max_length=20),
        ),
    ]
